### ISSUE TITLE
TXT record created with malformed name when using subdomain under a DNS zone

### ISSUE THREAD

**Issue by PTaylour** [snowdrop/godaddy-webhook#35]
I've been using the GoDaddy webhook with cert-manager on an on-prem cluster and I've encountered a situation that I'm hoping to get some clarification on.

We're running an internal DNS server with a specified DNS zone (`zone.mycompany.org`)

When I request a certificate for a sub-subdomain (e.g., `app.zone.mycompany.org`), the GoDaddy webhook seems to attempt to create the TXT record under `zone.mycompany.org` (as expected), but GoDaddy ends up creating the record under `mycompany.org` instead.

The `PUT` request made by the webhook:

```
PUT https://api.godaddy.com/v1/domains/zone.mycompany.org/records/TXT/_acme-challenge.app
```

results in the record being accessible at `_acme-challenge.app.mycompany.org` (`zone` is missing)

```sh
dig -t txt _acme-challenge.app.mycompany.org +short
"c-JuZ0H6dcsr1oVTk0INFciyviEi42Fnvn_mTxf5ErF"
```

and not at `_acme-challenge.app.zone.mycompany.org`

```sh
dig -t txt _acme-challenge.app.zone.mycompany.org +short

```

as I would expect.

I can work around this by telling cert-manager to use only public DNS servers:

```yaml
dns01RecursiveNameservers: "1.1.1.1:53,1.0.0.1:53"
dns01RecursiveNameserversOnly: true
```

Which results in the `PUT` request

```
PUT https://api.godaddy.com/v1/domains/mycompany.org/records/TXT/_acme-challenge.app.zone
```

and creates the TXT record at `_acme-challenge.app.zone.mycompany.org` as required.

However, I'm wondering if this implies there's a limitation or a specific configuration requirement when using DNS zones with the GoDaddy webhook? Or is this likely to be an issue with how we've configured the internal DNS server?

Thanks for your time and assistance!

### Additional information

Here's my config

```yaml
apiVersion: cert-manager.io/v1
kind: ClusterIssuer
metadata:
  name: letsencrypt-staging
spec:
  acme:
    server: https://acme-staging-v02.api.letsencrypt.org/directory
    email: me@mycompany.org
    privateKeySecretRef:
      name: letsencrypt-staging-account-key
    solvers:
    - selector:
        dnsNames:
        - app.zone.mycompany.org
      dns01:
        webhook:
          config:
            apiKeySecretRef:
              name: godaddy-api-key
              key: token
            production: true
            ttl: 1800
          groupName: acme.mycompany.com
          solverName: godaddy
---
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: ingress-cert
spec:
  secretName: ingress-cert-secret
  commonName: app.zone.mycompany.org
  dnsNames:
    - app.zone.mycompany.org
  duration: 2160h
  renewBefore: 360h
  issuerRef:
    name: letsencrypt-staging
    kind: ClusterIssuer
```
