### ISSUE TITLE
Error presenting challenge: the server could not find the requested resource

### ISSUE THREAD

**Issue by morzan1001** [snowdrop/godaddy-webhook#36]
Hello everyone, 

i have a problem requesting a certificate for a domain of mine. i have made the following configuration:

Certificate:
```
---
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: <NAME>
  namespace: cert-manager
spec:
  secretName: <NAME>
  renewBefore: 240h
  issuerRef:
    name: letsencrypt-production
    kind: ClusterIssuer
  commonName: "<NAME>"
  dnsNames:
  - "<NAME>"
  - "<NAME>"
```

Issuer:
```
---
apiVersion: cert-manager.io/v1
kind: ClusterIssuer
metadata:
  name: letsencrypt-production
spec:
  acme:
    server: https://acme-v02.api.letsencrypt.org/directory
    email: <EMAIL>
    privateKeySecretRef:
      name: letsencrypt-production
    solvers:
      - selector:
          dnsZones:
            - "<NAME>"
        dns01:
          webhook:
            config:
              apiKeySecretRef:
                name: godaddy-api-key
                key: token
              production: true
              ttl: 600
            groupName: acme.<NAME>
            solverName: godaddy
```

SecretKey:
```
---
apiVersion: v1
kind: Secret
metadata:
  name: godaddy-api-key
  namespace: cert-manager
type: Opaque
stringData:
  token: <TOKEN>
```

At first i got the error that a resource could not be created for the group i specified. The exact error looked like this:

```
Error presenting challenge: godaddy.acme.<NAME> is forbidden: User "system:serviceaccount:cert-manager:cert-manager" cannot create resource "godaddy" in API group "acme.<NAME>" at the cluster scope 
```

I then created a role-binding to set authorizations correctly if necessary. The whole thing looks like this:
```
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: dns-challenge-missing-role
rules:
- apiGroups: ["acme.<NAME>"]
  resources: ["godaddy"]
  verbs: ["*"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: dns-challenge-missing-role-binding
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: dns-challenge-missing-role
subjects:
- kind: ServiceAccount
  name: cert-manager
  namespace: cert-manager
```

Now I get the following error and can't get any further:
```
Error presenting challenge: the server could not find the requested resource (post godaddy.acme.<NAME>) 
```

Maybe someone here has an idea what i have done wrong, i am grateful for any tips :)

**Comment by cmoulliard** [comment]
> kubectl -n cert-manager describe challenge <NAME>

Can you paste the content of `YAML status` please reported by the following command ?
```
kubectl -n cert-manager get challenge <NAME> -oyaml
```

**Comment by morzan1001** [comment]
```
status:
  presented: false
  processing: true
  reason: the server is currently unable to handle the request (post godaddy.acme.mycompany.com)
  state: pending
```

I think this is the same output as in the last output I provided.

**Comment by morzan1001** [comment]
Yes, I think the API itself is not started correctly. The API service has the following status: 
```
status:
  conditions:
    - lastTransitionTime: '2023-12-02T12:50:20Z'
      message: >-
        endpoints for service/godaddy-webhook in "cert-manager" have no
        addresses with port name "https"
      reason: MissingEndpoints
      status: 'False'
      type: Available
```

The pod itself does not seem to start correctly (?) In any case, I cannot view any logs from the pod:
```
kubectl -n cert-manager get pods
```
```
NAME                                     READY   STATUS             RESTARTS         AGE
cert-manager-cainjector-c86f8699-2f2sv   1/1     Running            0                44h
cert-manager-7d9dc8684c-m5kjh            1/1     Running            0                44h
cert-manager-7d9dc8684c-zcwkw            1/1     Running            0                44h
cert-manager-7d9dc8684c-p9f7q            1/1     Running            0                44h
cert-manager-webhook-f8f64cb85-hsjkb     1/1     Running            0                44h
godaddy-webhook-576c45df5f-cwcrl         0/1     CrashLoopBackOff   528 (103s ago)   44h
```
