### ISSUE TITLE
Observed a panic: runtime error: index out of range [1] with length 1

### ISSUE THREAD

**Issue by mozai** [snowdrop/godaddy-webhook#38]
Using: godaddy-webhook 0.3.0 and jetstack/cert-manager:1.13.2

When I use the ClusterIssuer defined in README.md , changing `*.example.com` for `*.mozai.com` and `groupName: acme.mycompany.com` for `groupName: acme.mozai.com`, cert-manager complains:

> "cert-manager/orders: Failed to determine the list of Challenge resources needed for the Order" err="no configured challenge solvers can be used for this challenge" resource_name="grafana-tls-1-3645741348" resource_namespace="monitoring" resource_kind="Order" resource_version="v1"

Thinking the `selector` block in the ClusterIssuer's only solver might be what's not matching, I get a constant stream of golang panic stacktraces, starting with this error:

> runtime.go:77] Observed a panic: runtime error: index out of range [1] with length 1
> goroutine 2548 [running]:
> k8s.io/apiserver/pkg/endpoints/handlers/finisher.finishRequest.func1.1()
>        /go/pkg/mod/k8s.io/apiserver@v0.27.4/pkg/endpoints/handlers/finisher/finisher.go:105 +0xa5

What is causing "no solvers can be used for this challenge?  Surely `selector: { dnsNames: ['*.mozai.com'] }` does match grafana.mozai.com so is there somewhere else I should look?  and should the software be crashing that hard and that frequently if the selector is absent?

```
apiVersion: cert-manager.io/v1
kind: ClusterIssuer
metadata:
  name: letsencrypt-godaddy-prod
spec:
  acme:
    email: hostmaster.mozai.com  # dont post email addresses to webpages
    privateKeySecretRef:
      name: letsencrypt-godaddy-prod
    server: https://acme-v02.api.letsencrypt.org/directory
    solvers:
    - dns01:
        webhook:
          config:
            apiKeySecretRef:
              name: godaddy-api-key
              key: token
            production: true
            ttl: 600
          groupName: acme.mozai.com
          solverName: godaddy
      selector: {dnsNames: ['*.mozai.com']}
```

**Comment by mozai** [comment]
According to [cert-manager doccos about ClusterIssuers](https://cert-manager.io/docs/reference/api-docs/#acme.cert-manager.io/v1.ACMEChallengeSolver), the `selector` configuration for a solver should be optional, so I don't expect the software to freak out if it's absent.  
The `selector` [CertificateDNSNameSelector](https://cert-manager.io/docs/reference/api-docs/#acme.cert-manager.io/v1.CertificateDNSNameSelector) can have up to three keys: matchLabels, dnsNames, and dnsZones, and it doesn't mention that wildcards like `*.example.com` can be used in dnsNames.  I'll try using dnsZones instead.

... yes, cert-manager is now reporting 
> I1205 01:21:10.018369       1 dns.go:88] "cert-manager/challenges/Present: presenting DNS01 challenge for domain" resource_name="grafana-tls-1-3645741348-3450699660" resource_namespace="monitoring" resource_kind="Challenge" resource_version="v1" dnsName="grafana.mozai.com" type="DNS-01" resource_name="grafana-tls-1-3645741348-3450699660" resource_namespace="monitoring" resource_kind="Challenge" resource_version="v1" domain="grafana.mozai.com"
> E1205 01:21:10.027946       1 controller.go:167] "cert-manager/challenges: re-queuing item due to error processing" err="the server is currently unable to handle the request (post godaddy.acme.mozai.com)" key="monitoring/grafana-tls-1-3645741348-3450699660"

But the godaddy-webhook pod is still crashingi and dumping stack traces starting with

> E1205 01:23:30.073065       1 runtime.go:77] Observed a panic: runtime error: index out of range [1] with length 1

**Comment by cmoulliard** [comment]
Here is an example about a Certificate + Issuer that I'lm using to renew the following 
`*` + domain name  =>`*.apps.qshift.snowdrop.dev` successfully:
```
apiVersion: cert-manager.io/v1
kind: Issuer
metadata:
  name: letsencrypt-prod-qshift-snowdrop-dev
  labels:
    app: qshift-ca-cert
  namespace: snowdrop-site
spec:
  acme:
    server: https://acme-v02.api.letsencrypt.org/directory
    email:
    privateKeySecretRef:
      name: letsencrypt-prod-snowdrop-dev
    solvers:
      - dns01:
          webhook:
            config:
              apiKeySecretRef:
                name: godaddy-api-key
                key: token
              production: true
              ttl: 600
            groupName: acme.mycompany.com
            solverName: godaddy
        selector:
          dnsNames:
            - '*.apps.qshift.snowdrop.dev'
---
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: qshift-snowdrop-dev
  labels:
    app: qshift-ca-cert
  namespace: snowdrop-site
spec:
  renewBefore: 2136h
  duration: 2190h
  privateKey:
    size: 2048
    algorithm: RSA
  issuerRef:
    kind: Issuer
    name: letsencrypt-prod-qshift-snowdrop-dev
  secretName: qshift-snowdrop-dev-tls
  dnsNames:
    - '*.apps.qshift.snowdrop.dev'
```
