### ISSUE TITLE
Missing permissions for webhook deployment

### ISSUE THREAD

**Issue by fuero** [snowdrop/godaddy-webhook#44]
The helm chart generated godaddy-webhook clusterrole is missing this rule to work (tested on OpenShift 4.15):

```yaml
- apiGroups:                                                                                                                                                                                      
  - ""                                                                                                                                                                                            
  resources:                                                                                                                                                                                      
  - configmaps                                                                                                                                                                                    
  verbs:                                                                                                                                                                                          
  - get                                                                                                                                                                                           
  - watch                                                                                                                                                                                         
  - list
```
