### ISSUE TITLE
Misleading cluster issuer example

### ISSUE THREAD

**Issue by fuero** [snowdrop/godaddy-webhook#45]
The example clusterIssuer has a selector that's only valid for issuing a wildcard certificate.

I propose changing the example from:

```yaml
selector:
  dnsNames:
   - "*.example.com"
```

to:

```yaml
selector:
  dnsZones:
   - "example.com"
```
