### ISSUE TITLE
Broken --v flag in release 0.4.0

### ISSUE THREAD

**Issue by CompPhy** [snowdrop/godaddy-webhook#53]
When deploying the 0.4.0 release, I get this error on startup:  `Error: unknown flag: --v 2`

I was able to modify my deployment to use `--v=2` instead of `--v 2` and that seems to fix the issue.  This is probably just a small typo in the helm template.

**Comment by cmoulliard** [comment]
> I was able to modify my deployment to use `--v=2` instead of `--v 2` and that seems to fix the issue. This is probably just a small typo in the helm template.

What did you do to got such an error ?

**Comment by CompPhy** [comment]
I'm using FluxCD for automatic helm deployment, but otherwise I'm just doing a fairly standard setup.  I literally only have one value set in my chart, and everything else is taking the defaults.  My current config is included at the bottom, which I had to roll back to 0.3.0 until this issue is addressed.  Updating to 0.4.0 is what broke it, I only changed the version number as none or our other settings need to change on this upgrade.

For context on the "typo" comment... I'm pretty sure the issue is here:  https://github.com/snowdrop/godaddy-webhook/blob/8cab3d686772572a1dc62af8a16344bf5f42948a/deploy/charts/godaddy-webhook/templates/deployment.yaml#L33

As you can see, the other parameters use `=` for but some reason the --v option was added with a space instead.  I'm pretty sure just changing to equal sign will make things a lot more consistent. 

```
---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: godaddy-webhook
  namespace: cert-manager
spec:
  interval: 5m
  chart:
    spec:
      chart: godaddy-webhook
      version: 0.3.0
      sourceRef:
        kind: HelmRepository
        name: godaddy-webhook    # This points to https://snowdrop.github.io/godaddy-webhook until quay tagging is fixed.
        namespace: cert-manager
      interval: 1m
  values:
    groupName: <REDACTED FQDN>
```
